In [2]:
import numpy as np

print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n') # все типы данных numpy

mystery = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)
print(mystery.ndim) # размерность массива
print(mystery.shape) # максимальная протяжённость по одной из осей массива
print(mystery.size) # число элементов массива
print(mystery.dtype) # тип данных у элементов массива
print(mystery.itemsize) # вес элемента в массива в байтах


<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>
2
(3, 3)
9
int16
2


In [3]:
# Выполните все действия с массивом
mystery2 = np.array([
            [-13586, 15203, 28445, -27117, -1781, -17182, -18049],
            [25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
            [13348, 28049, 28655, -6012, 21762, 25397,  8225],
            [13240, 7994, 32592, 20149, 13754, 11795, -564],
            [-21725, -8681, 30305, 22260, -17918, 12578, 29943],
            [-16841, -25392, -17278, 11740, 5916, -47, -32037]])
# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery2[4, 2]
print(elem_5_3)
# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery2[5, 6]
print(last)
# В переменную line_4 сохраните строку 4
line_4 = mystery2[3]
print(line_4)
# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery2[:, -2]
print(col_2)
# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# Результат сохраните в переменную part
part = mystery2[1:4, 2:5]
print(part)
#  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery2[:, 6][::-1]
print(rev)
# Сохраните в переменную trans транспонированный массив
trans = mystery2.transpose()
print(trans)

30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]
[-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


In [5]:
# Выполните все действия, указанные в комментариях в файле
import numpy as np
mystery = np.array ([ 12279., -26024., 28745., nan, 31244., -2365., -6974., -9212., nan, -17722., 16132., 25933., nan, -16431., 29810.])
print (mystery)
# Получите булевый массив с информацией о np.nan в массиве mystery
# True - значение пропущено, False - значение не пропущено
nans_index = np.isnan(mystery)
print(nans_index)
# В переменную n_nan сохраните число пропущенных значений
n_nan = 3

# Заполните пропущенные значения в массиве mystery нулями
mystery[np.isnan(mystery)] = 0
print(mystery)

# Поменяйте тип данных в массиве mystery на int32
mystery=np.int32(mystery)
print(mystery)

# Отсортируйте значения в массиве по возрастанию и сохраните
# результат в переменную array
array = np.sort(mystery)

# Сохраните в массив table двухмерный массив, полученный из массива array
# В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
# по столбцам! Например, 1, 2, 3, 4 -> 1    3
#                                      2    4
table = array.reshape((5, 3), order='F')
print(table)
#  Сохраните в переменную col средний столбец из table
col = table[:,1]
print(col)


NameError: name 'nan' is not defined

In [6]:
#Векторы в геометрии, которые параллельны друг другу, называются сонаправленными
#Также векторы могут быть параллельны и в пространстве. На практике есть несколько способов определить сонаправленность векторов. 
#Один из них: сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов.
#С помощью этого критерия найдите пару сонаправленных векторов:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])
length_a = np.linalg.norm(a)
length_b = np.linalg.norm(b)
length_c = np.linalg.norm(c)
print (length_a + length_b==np.linalg.norm(a + b))
print (length_a + length_c==np.linalg.norm(a + c))
print (length_b + length_c==np.linalg.norm(b + c))
# Найдите пару векторов, расстояние между которыми больше 100
print (np.linalg.norm(a - b))
print (np.linalg.norm(a - c))
print (np.linalg.norm(b - c))
#Найдите пару перпендикулярных векторов с помощью скалярного произведения (оно должно быть равно нулю)
print(np.dot(a, b))
print(np.dot(a, c))
print(np.dot(c, b))


False
True
False
85.901105930017
49.13247398615299
120.6358155772986
34
4828
68


In [7]:
#Найдите минимальное значение в массиве mystery
print(mystery.min())
#Найдите максимальное значение в массиве mystery
print(np.max(mystery))
#Найдите среднее значение массива. Ответ не округляйте.
print(mystery.mean())
#Найдите медиану массива.
print(np.median(mystery))
#Найдите стандартное отклонение значений в массиве. Ответ округлите до сотых.
print(round(np.std(mystery),2))


12
98
47.111111111111114
45.0
30.3


In [8]:
#Задайте seed равным 2021.Сохраните в переменные необходимые значения.
import numpy as np
# Не забудьте импортировать numpy и сразу задать seed 2021
np.random.seed(2021)
# В simple сохранте случайное число в диапазоне от 0 до 1
simple = np.random.rand() 
print(simple)
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)
print(randoms)
# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
#table = np.random.uniform(1, 101, size=(3,2))
table = np.random.randint(1, 101, size=(3,2))
print(table)
# В переменную even сохраните четные числа от 2 до 16 (включительно)
#even = np.random.randint(1, 9, size=8)*2
even = np.arange(1,9)*2
print(even)
# Перемешайте числа в even так, чтобы массив even изменился
np.random.shuffle(even)
print(even)
# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, size=3, replace=False)
print(select)
# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)
print(triplet)

0.6059782788074047
[ 1.44214488e+03  1.51654277e+02  5.28813265e+02  2.01501516e+03
  1.28240517e+02  2.38594033e+02  1.48460111e+03  1.28755048e+03
  1.55273730e+03  6.03577336e+01 -2.28417401e+01  1.93936169e+03
  1.18854621e+03  3.80736459e+01  1.06852230e+03  1.18847514e+03
  1.94250320e+03  1.09681462e+03  6.55790201e+02  8.31607324e+02
  2.88216888e+02  1.08596141e+03  2.73553360e+02  1.11722142e+03
  8.84076551e+02  9.74175063e+02  1.63694713e+03  1.43966053e+03
 -7.88273550e-02  1.30919192e+03  1.24700551e+03  1.64761920e+03
  2.93903055e+02  1.19056852e+03  1.19102890e+03  5.03619976e+02
  1.74254881e+03  1.13013901e+03  1.98142287e+03  8.10086179e+02
  1.24235695e+02  9.54671885e+02  7.87407805e+02  1.83850479e+03
  1.38927296e+03  1.78361285e+03  1.12847065e+03  1.23255777e+03
  5.92935602e+02  1.63845066e+03  5.12482326e+02  5.17676863e+02
  2.87071500e+02  4.25673103e+02  1.26315547e+03  1.85668749e+02
  6.93866612e+02  1.25597031e+03  1.69165738e+03 -1.14109610e+01
  7.49

In [9]:
#Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. 
#Гарантируется, что все векторы, которые передаются, одинаковой длины.
#Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.
import numpy as np
def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
    return (min(dists), max(dists))

In [10]:
#Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. 
#Гарантируется, что все векторы, которые передаются, одинаковой длины.
#Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.
import numpy as np
def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

In [11]:
#Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). 
#Это поля для игры в лото.
#Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).
#Функция возвращает полученный массив.
import numpy as np
def get_loto(num):
    loto = np.random.randint(1, 101, size=(num, 5, 5))
    return loto

In [12]:
#Напишите функцию get_unique_loto(num). 
#Она так же, как и функция в задании 10.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.
#Функция также должна возвращать массив формы num x 5 x 5.
import numpy as np
def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res